# Generated by Django 4.0.10 on 2024-05-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('object', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Personalize',
                'db_table': 'personalize',
            },
        ),
    ]
