# Generated by Django 4.0.10 on 2024-06-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_generatedstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_imgs', to='story.story', verbose_name='Story imgs')),
            ],
            options={
                'verbose_name': 'Story images',
                'verbose_name_plural': 'Story images',
                'db_table': 'story_images',
            },
        ),
    ]
