# Generated by Django 4.0.10 on 2024-06-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_storyimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyimages',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_imgs', to='story.story', verbose_name='Story'),
        ),
    ]
