# Generated by Django 4.0.10 on 2024-06-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_story_context_story_historical_significance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='main_happenings',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
