# Generated by Django 4.0.10 on 2024-06-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_alter_story_main_happenings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'System setting',
                'verbose_name_plural': 'System settings',
                'db_table': 'system_settings',
            },
        ),
    ]
