# Generated by Django 4.0.10 on 2024-07-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedstory',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
