# Generated by Django 4.0.10 on 2024-07-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_generatedstory_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedstory',
            name='narrator',
            field=models.IntegerField(default=3),
        ),
    ]
