# Generated by Django 4.0.10 on 2024-07-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_generatedstory_narrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyimages',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
